version: 2
jobs:
  publish:
    docker:
      - image: rishabhpoddar/django
    steps:
      - checkout
      - run: pip install setuptools wheel==0.31.0 twine
      - run: python3.7 setup.py sdist bdist_wheel
      - run: twine upload --username $USERNAME --password $PASSWORD dist/*

  test:
    docker:
      - image: rishabhpoddar/django
    steps:
      - checkout
      - run: make dev-install
      - run: make test

workflows:
  version: 2
  tagged-build:
    jobs:
      - publish:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
      - test:
          filters:
            branches:
              only: 
                - dev
                - master